apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetris-{{ .Values.env }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tetris
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: apps/tetris/{{ .Values.env }}
  
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true